import os
from dotenv import load_dotenv
from google import genai

load_dotenv()

MODEL_NAME = "gemini-3.8-flash"


class SecurityReviewAgent:
    def __init__(self, api_key: str):
        self.client = genai.Client(api_key=api_key)

    def run(self, source_code: str, ast_metadata: dict) -> str:
        prompt = f"""
You are an expert SAST Security Review Agent.
Analyze the following Python source code and its AST metadata.

AST Metadata:
{ast_metadata}

Source Code:
{source_code}

Identify architectural/security risks (with CWE IDs) and assign an overall severity rating (LOW, MEDIUM, HIGH, CRITICAL).
Format output with headers:
### 1. Architectural & Safety Risks Found
### 2. Severity Rating
"""
        # Use interactions endpoint as required by the API
        interaction = self.client.interactions.create(
            model=MODEL_NAME,
            input=prompt
        )
        return interaction.output_text


class RefactoringAgent:
    def __init__(self, api_key: str):
        self.client = genai.Client(api_key=api_key)

    def run(self, source_code: str, security_findings: str) -> str:
        prompt = f"""
You are an expert Secure Code Refactoring Agent.
Based on the original source code and the security findings generated by the Security Review Agent, provide a refactored, secure version of the code.

Original Source Code:
{source_code}

Security Review Findings:
{security_findings}

Format output with header:
### 3. Recommended Code Refactoring
Provide the complete refactored Python code block with brief comments explaining the fixes.
"""
        interaction = self.client.interactions.create(
            model=MODEL_NAME,
            input=prompt
        )
        return interaction.output_text


def run_multi_agent_audit(source_code: str, ast_metadata: dict) -> str:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY environment variable is not set.")

    print(" -> [Agent 1] SecurityReviewAgent is analyzing code & AST metadata...")
    reviewer = SecurityReviewAgent(api_key)
    findings = reviewer.run(source_code, ast_metadata)
    print(" -> [Agent 1] Analysis complete!")

    print(" -> [Agent 2] RefactoringAgent is generating secure code fixes...")
    refactorer = RefactoringAgent(api_key)
    refactored_code = refactorer.run(source_code, findings)
    print(" -> [Agent 2] Refactoring complete!")

    return f"{findings}\n\n{refactored_code}"